# -*- coding: utf-8 -*-
"""Dynamic Pricing...ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xJXKP6vbTD2fZDm8gHSO9hWEW4tLZWwC
"""

#hello Shashwat..Vaibhav
import matplotlib.pyplot as plt
#define alphas for two competitors..
alpha_a,alpha_b=0.6, 0.4

#define initial customer base (a)...will give demand in number of persons that are interested.
A, B = 20,20

#define marginal cost of the two competitors..
marginal_a, marginal_b = 125,125

#defining brand loylty of the consumer base
C_a, C_b = 0.5, 0.6

#define behavior of buyers to price change
G_a = [0,0]
G_b = [0,0]

#define how less attractive product is at the initial price...
b_a, b_b = 0.4 , 0.48

#Now we will calculate the the complete price variation over the period of time T
P_a =[]
P_b =[]

index = 0
t = 10
cost =170# int(input('Give the initial price for the Competitor B(>125) :'))
r_b = 150# int(input('Give the initial reference for the Competitor B(>125) :'))
P_b.append(cost)
r_a =140# int(input('Give the initial reference for the Competitor A(>125) :'))
S = []
while index<t:
    price = A+ G_a[0] * (r_a + marginal_a) + b_a* marginal_a + C_a * P_b[index]
    price = price/(2*b_a + G_a[0])
    price = round(price,2)
    P_a.append(price)
    print('The expected price Firm A should have for its product is :', P_a[index])
    r_a = alpha_a * r_a + (1-alpha_a) * price
    print('------------------------------------------------------------------------')
    price = B+ G_b[0] * (r_b + marginal_b) + marginal_b * b_b + C_b * P_a[index]
    price = price/(2*b_b + G_b[0])
    price = round(price,2)
    r_b = alpha_b * r_b + (1-alpha_b) * price
    P_b.append(price)
    print ('Now the Firm B reacts(to above change by A) by changing its price to...',P_b[index+1])
    index+=1
    S.append(index)
P_b.pop()
plt.scatter(S, P_a,color = 'red',label='Firm i')
plt.scatter(S, P_b, color = 'blue', label = 'Firm j')
plt.legend(loc='lower right')
plt.xlabel("Time Period")
plt.ylabel("Price")
plt.title("Dynamic Price change between Firm i and Firm j")
plt.savefig('plot.png')